//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartMaster
    {
        public ChartMaster()
        {
            this.ChartDetail = new HashSet<ChartDetail>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<ChartDetail> ChartDetail { get; set; }
    }
}
