//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartDetail
    {
        public int Id { get; set; }
        public string SectorName { get; set; }
        public string SectorValue { get; set; }
        public string SectorColor { get; set; }
        public Nullable<int> ChartId { get; set; }
    
        public virtual ChartMaster ChartMaster { get; set; }
    }
}
